apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
      - key: env
        operator: In
        values:
          - dev
          - sit
          - uat
  template:
    metadata:
      name: pod-name
      labels:
        app: nginx
        env: sit
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80