apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotations
  labels:
    team: operations
    version: 1.1.14
    environtment: development
  annotations:
    description: Ini adalah aplikasi yang dibuat menggunakan golang 1.16
    apapun: Apapun itu ...
spec:
  containers:
    - name: nginx
      image: nginx:1.17.8
      ports:
        - containerPort: 80